plugins {
    id("heimdall.java8")
    `java-library`
}

// The platform-free half of the shell: loading, staging, swapping and rolling back a core, plus
// the pieces of shell state every platform needs (command relays, the login gate, the tunnel
// delegate). Platform-free by the same conformance rule as core, so each of the three platform
// shells is only the glue between this and one server API.
dependencies {
    api(project(":shell-api"))
    api(project(":api"))
}

/**
 * The shell's own version, as a compile-time constant.
 *
 * Velocity's @Plugin annotation needs one, and it can no longer borrow core's BuildConstants: the
 * core is a separate artifact in a separate classloader, and the shell's version is the one the
 * platform should report, because the shell is what the platform actually loaded.
 */
val generateShellConstants by tasks.registering {
    val versionValue = project.version.toString()
    val outputDir = layout.buildDirectory.dir("generated/sources/shellconstants/java/main")
    inputs.property("version", versionValue)
    outputs.dir(outputDir)
    doLast {
        val pkgDir = outputDir.get().asFile.resolve("com/heimdall/shell")
        pkgDir.mkdirs()
        pkgDir.resolve("ShellBuildConstants.java").writeText(
            """
            package com.heimdall.shell;

            /** Generated by the Gradle build. Do not edit. */
            public final class ShellBuildConstants {

                /** The shell's version, as declared in gradle.properties or passed with -Pversion. */
                public static final String VERSION = "$versionValue";

                private ShellBuildConstants() {
                }
            }
            """.trimIndent() + "\n",
        )
    }
}

sourceSets {
    named("main") {
        java.srcDir(generateShellConstants)
    }
}
