plugins {
    id("heimdall.java8")
    `java-library`
}

// The platform-free half of the shell: loading, staging, swapping and rolling back a core, plus
// the pieces of shell state every platform needs (command relays, the login gate, the tunnel
// delegate). Platform-free by the same conformance rule as core, so each of the three platform
// shells is only the glue between this and one server API.
dependencies {
    api(project(":shell-api"))
    api(project(":api"))
}

/**
 * The shell's own version, as a compile-time constant.
 *
 * Velocity's @Plugin annotation needs one, and it can no longer borrow core's BuildConstants: the
 * core is a separate artifact in a separate classloader, and the shell's version is the one the
 * platform should report, because the shell is what the platform actually loaded.
 */
val generateShellConstants by tasks.registering {
    val versionValue = project.version.toString()
    val outputDir = layout.buildDirectory.dir("generated/sources/shellconstants/java/main")
    inputs.property("version", versionValue)
    outputs.dir(outputDir)
    doLast {
        val pkgDir = outputDir.get().asFile.resolve("com/heimdall/shell")
        pkgDir.mkdirs()
        pkgDir.resolve("ShellBuildConstants.java").writeText(
            """
            package com.heimdall.shell;

            /** Generated by the Gradle build. Do not edit. */
            public final class ShellBuildConstants {

                /** The shell's version, as declared in gradle.properties or passed with -Pversion. */
                public static final String VERSION = "$versionValue";

                private ShellBuildConstants() {
                }
            }
            """.trimIndent() + "\n",
        )
    }
}

sourceSets {
    named("main") {
        java.srcDir(generateShellConstants)
    }
}

// ── Fixture cores for the tests ────────────────────────────────────────────
//
// Real jars, loaded by the tests through a real child URLClassLoader, exactly as a production core
// is. Their classes are compiled in their own source set and deliberately kept OFF the test
// classpath: parent-first delegation would otherwise resolve them from the test loader, and the
// loader's "the entry point must come from the core jar" check would (rightly) refuse every one.
//
// One class, several jars; heimdall-fixture.properties in each picks the behaviour. See
// FixtureCore for what each variant does.
val fixtureCore: SourceSet = sourceSets.create("fixtureCore")

dependencies {
    "fixtureCoreCompileOnly"(project(":shell-api"))
}

val fixtureCoreContracts = mapOf(
    "alpha" to "1",
    "beta" to "1",
    "failing" to "1",
    "contradicts" to "1",
    "leaky" to "1",
    "fragile" to "1",
    "contract2" to "2",
)

val fixtureCoreJars = fixtureCoreContracts.map { (variant, contract) ->
    tasks.register<Jar>("fixtureCore" + variant.replaceFirstChar { it.uppercase() }) {
        archiveFileName.set("fixture-core-$variant.jar")
        destinationDirectory.set(layout.buildDirectory.dir("fixture-cores"))
        from(fixtureCore.output)
        from("src/fixtureCore/services")
        from("src/fixtureCore/variants/$variant")
        manifest {
            attributes(
                "Heimdall-Shell-Contract" to contract,
                "Heimdall-Core-Version" to "1.0.0-$variant",
            )
        }
    }
}

tasks.test {
    dependsOn(fixtureCoreJars)
    inputs.files(fixtureCoreJars)
    systemProperty(
        "heimdall.fixtureCores",
        layout.buildDirectory.dir("fixture-cores").get().asFile.absolutePath,
    )
}
