plugins {
    id("heimdall.java8")
}

dependencies {
    // Deliberately `implementation`, not `api`: the shaded libraries are core's
    // private business. A feature module that needs JSON or YAML goes through a
    // core utility rather than importing Gson or SnakeYAML itself. That keeps the
    // relocation surface in one place and makes swapping any of these out a
    // core-local change instead of a repo-wide one.
    //
    // Real code exercises both from Java 8 source — Gson in `mirror`, SnakeYAML in `config` —
    // which is what proves their APIs are reachable at this source level. The shipped bytecode
    // levels are proven separately by :app:verifyShadowJar, the only check that actually
    // catches them.
    implementation(libs.gson)
    implementation(libs.snakeyaml)

    // The WebSocket client carries one constraint that is not obvious from the
    // outside: it must stay zero-dependency and free of any logging facade.
    // Java-WebSocket — the obvious pick, and what v2 avoided — calls
    // org.slf4j.LoggerFactory unconditionally from the AbstractWebSocket,
    // WebSocketImpl and Draft_6455 constructors, and Spigot 1.8.8-1.16 ships no
    // slf4j at all. That is a guaranteed NoClassDefFoundError across the whole
    // legacy range the moment a socket is constructed, not a degraded-logging
    // inconvenience. nv-websocket-client has no transitive dependencies and no
    // logging facade at all.
    //
    // Phase 1b wraps this behind a core-owned socket interface so the library stays swappable if
    // that constraint ever changes. Nothing in core references it yet — it stays declared because
    // Shadow bundles the runtime classpath whether or not our own code names a class, and
    // :app:verifyShadowJar requires the com/heimdall/libs/nvws/ relocation to be populated.
    implementation(libs.nv.websocket.client)
}

// The Velocity `@Plugin` annotation needs the version as a compile-time
// constant, so it is generated into core (Java 8) and read out of the constant
// pool by the Java 17 Velocity module.
val generateBuildConstants by tasks.registering {
    val versionValue = project.version.toString()
    val outputDir = layout.buildDirectory.dir("generated/sources/buildconstants/java/main")
    inputs.property("version", versionValue)
    outputs.dir(outputDir)
    doLast {
        val pkgDir = outputDir.get().asFile.resolve("com/heimdall/core")
        pkgDir.mkdirs()
        pkgDir.resolve("BuildConstants.java").writeText(
            """
            package com.heimdall.core;

            /** Generated by the Gradle build — do not edit. */
            public final class BuildConstants {

                /** The plugin version, as declared in gradle.properties. */
                public static final String VERSION = "$versionValue";

                private BuildConstants() {
                }
            }
            """.trimIndent() + "\n",
        )
    }
}

sourceSets {
    named("main") {
        java.srcDir(generateBuildConstants)
    }
}
