plugins {
    id("heimdall.java8")
}

dependencies {
    // Shaded at the app layer; every version here is pinned to a line that still
    // produces / accepts Java 8 bytecode. `CoreSanity` touches one class from
    // each so `--release 8` proves the claim at compile time rather than us
    // trusting the changelogs.
    implementation("com.google.code.gson:gson:2.10.1")
    implementation("org.java-websocket:Java-WebSocket:1.6.0")
    implementation("org.yaml:snakeyaml:2.4")
}

// The Velocity `@Plugin` annotation needs the version as a compile-time
// constant, so it is generated into core (Java 8) and read out of the constant
// pool by the Java 17 Velocity module.
val generateBuildConstants by tasks.registering {
    val versionValue = project.version.toString()
    val outputDir = layout.buildDirectory.dir("generated/sources/buildconstants/java/main")
    inputs.property("version", versionValue)
    outputs.dir(outputDir)
    doLast {
        val pkgDir = outputDir.get().asFile.resolve("com/heimdall/core")
        pkgDir.mkdirs()
        pkgDir.resolve("BuildConstants.java").writeText(
            """
            package com.heimdall.core;

            /** Generated by the Gradle build — do not edit. */
            public final class BuildConstants {

                /** The plugin version, as declared in gradle.properties. */
                public static final String VERSION = "$versionValue";

                private BuildConstants() {
                }
            }
            """.trimIndent() + "\n",
        )
    }
}

sourceSets {
    named("main") {
        java.srcDir(generateBuildConstants)
    }
}
